// <auto-generated />
using EfCore5Test.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCore5Test.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20201113224410_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EfCore5Test.Db.FirstModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("Firsts");
                });

            modelBuilder.Entity("EfCore5Test.Db.MyCoolModel", b =>
                {
                    b.Property<int>("FirstId")
                        .HasColumnType("int")
                        .HasColumnName("MyCoolModel_FirstId");

                    b.Property<int>("SecondId")
                        .HasColumnType("int")
                        .HasColumnName("MyCoolModel_SecondId");

                    b.Property<string>("SomeText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FirstId", "SecondId");

                    b.HasIndex("SecondId");

                    b.ToTable("MyCoolModels");
                });

            modelBuilder.Entity("EfCore5Test.Db.SecondModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("Seconds");
                });

            modelBuilder.Entity("EfCore5Test.Db.MyCoolModel", b =>
                {
                    b.HasOne("EfCore5Test.Db.FirstModel", "First")
                        .WithMany()
                        .HasForeignKey("FirstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfCore5Test.Db.SecondModel", "Second")
                        .WithMany()
                        .HasForeignKey("SecondId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EfCore5Test.Db.MyCoolKey", "Id", b1 =>
                        {
                            b1.Property<int>("MyCoolModelFirstId")
                                .HasColumnType("int");

                            b1.Property<int>("MyCoolModelSecondId")
                                .HasColumnType("int");

                            b1.Property<int>("FirstId")
                                .HasColumnType("int")
                                .HasColumnName("FirstId");

                            b1.Property<int>("SecondId")
                                .HasColumnType("int")
                                .HasColumnName("SecondId");

                            b1.HasKey("MyCoolModelFirstId", "MyCoolModelSecondId");

                            b1.ToTable("MyCoolModels");

                            b1.WithOwner()
                                .HasForeignKey("MyCoolModelFirstId", "MyCoolModelSecondId");
                        });

                    b.Navigation("First");

                    b.Navigation("Id");

                    b.Navigation("Second");
                });
#pragma warning restore 612, 618
        }
    }
}
