// <auto-generated />
using EfCore5Test.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCore5Test.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EfCore5Test.Db.MyCoolModel", b =>
                {
                    b.Property<int>("FirstId")
                        .HasColumnType("int")
                        .HasColumnName("MyCoolModel_FirstId");

                    b.Property<int>("SecondId")
                        .HasColumnType("int")
                        .HasColumnName("MyCoolModel_SecondId");

                    b.Property<string>("SomeText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FirstId", "SecondId");

                    b.ToTable("my_cools", "cool_stuff");
                });

            modelBuilder.Entity("EfCore5Test.Db.MyCoolModel", b =>
                {
                    b.OwnsOne("EfCore5Test.Db.MyCoolKey", "Id", b1 =>
                        {
                            b1.Property<int>("MyCoolModelFirstId")
                                .HasColumnType("int");

                            b1.Property<int>("MyCoolModelSecondId")
                                .HasColumnType("int");

                            b1.Property<int>("FirstId")
                                .HasColumnType("int")
                                .HasColumnName("FirstId");

                            b1.Property<int>("SecondId")
                                .HasColumnType("int")
                                .HasColumnName("SecondId");

                            b1.HasKey("MyCoolModelFirstId", "MyCoolModelSecondId");

                            b1.ToTable("my_cools");

                            b1.WithOwner()
                                .HasForeignKey("MyCoolModelFirstId", "MyCoolModelSecondId");
                        });

                    b.Navigation("Id");
                });
#pragma warning restore 612, 618
        }
    }
}
